In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4])

In [3]:
print(arr1)

[1 2 3 4]


In [5]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
zoro_arr=np.zeros((2,3))

In [7]:
print(zoro_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
one_arr=np.ones((3,2))

In [9]:
print(one_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
arr_1=np.array([[1,2,3],[4,5,6]])
arr_2=np.array([[7,8,9],[10,11,12]])
print(arr_1)

[[1 2 3]
 [4 5 6]]


In [14]:
print(arr_2)

[[ 7  8  9]
 [10 11 12]]


In [15]:
print(arr_1+arr_2)

[[ 8 10 12]
 [14 16 18]]


In [16]:
print(2*arr_1)

[[ 2  4  6]
 [ 8 10 12]]


In [17]:
print(arr_2)

[[ 7  8  9]
 [10 11 12]]


In [20]:
print(arr_2[0:2,])

[[ 7  8  9]
 [10 11 12]]


In [21]:
print(arr_2[,2])

SyntaxError: invalid syntax (3116488845.py, line 1)

In [23]:
print(arr_2[:,3])

IndexError: index 3 is out of bounds for axis 1 with size 3

In [24]:
print(arr_2)

[[ 7  8  9]
 [10 11 12]]


In [25]:
print(arr_1)

[[1 2 3]
 [4 5 6]]


In [26]:
print(np.sum(arr_1))

21


In [29]:
print(np.sum(arr_1[:,0:2],axis=0))

[5 7]


In [30]:
print(np.mean(arr_1))

3.5


In [31]:
import numpy as np

# Creating a sample array
arr_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Arithmetic Operations
result_addition = np.add(arr_1, 2)   # Add 2 to each element
result_multiply = np.multiply(arr_1, 3)  # Multiply each element by 3

# Trigonometric Functions
result_sin = np.sin(arr_1)  # Compute sine of each element
result_cos = np.cos(arr_1)  # Compute cosine of each element

# Exponential and Logarithmic Functions
result_exp = np.exp(arr_1)  # Compute e^x for each element
result_log = np.log(arr_1)  # Compute natural logarithm for each element

# Comparisons
result_greater_than_5 = arr_1 > 5  # Create a boolean array indicating elements greater than 5

# Element-wise Maximum
result_max = np.maximum(arr_1, 5)  # Element-wise maximum with 5

# Element-wise Square Root
result_sqrt = np.sqrt(arr_1)  # Compute square root of each element


In [ ]:
import numpy as np

# Creating sample matrices
matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[5, 6], [7, 8]])

# Matrix Multiplication
matrix_multiply = np.dot(matrix_A, matrix_B)

# Determinant Calculation
matrix_det_A = np.linalg.det(matrix_A)

# Eigenvalue Computation
eigenvalues, eigenvectors = np.linalg.eig(matrix_A)


In [ ]:
# Generating Random Numbers
random_number = np.random.rand()  # Random float between 0 and 1
random_array = np.random.rand(3, 4)  # 3x4 array of random floats between 0 and 1

# Random Sampling from a Distribution
random_int = np.random.randint(1, 10, size=(2, 3))  # 2x3 array of random integers between 1 and 10
random_normal = np.random.normal(loc=0, scale=1, size=(3, 3))  # 3x3 array sampled from a normal distribution


In [ ]:
# Calculating Mean, Median, Standard Deviation, and Variance
data = np.array([1, 2, 3, 4, 5])

mean_value = np.mean(data)
median_value = np.median(data)
std_deviation = np.std(data)
variance = np.var(data)
